import QtQuick 6.5
import QtQuick.Controls 6.5
// TODO Qt6: Old Calendar component (QtQuick.Controls 1.4) removed in Qt 6
// Need to reimplement using Qt6 Calendar components (DayOfWeekRow, MonthGrid, etc.)
// For now, calendar is disabled to allow application to load

Rectangle {
    id: calendarPlaceholder
    width: hscale(300)
    height: vscale(300)
    color: "#f0f0f0"
    border.color: "#cccccc"
    border.width: 1
    radius: 5
    
    // Properties for compatibility with old Calendar API
    property real scaleFactorHeight: 1
    property real scaleFactorWidth: 1
    property date minimumDate: new Date(1900, 0, 1)
    property date maximumDate: new Date(2100, 11, 31)
    property date selectedDate: new Date()
    
    // selectedDateChanged signal is auto-generated by property date selectedDate
    
    function hscale(size) {
        return Math.round(size * scaleFactorWidth)
    }
    function vscale(size) {
        return Math.round(size * scaleFactorHeight)
    }
    function tscale(size) {
        return Math.round((hscale(size) + vscale(size)) / 2)+2
    }
    
    Text {
        anchors.centerIn: parent
        text: "Calendar temporarily disabled\n(Qt 6 migration in progress)\n\nPlease type date manually"
        color: "#666666"
        font.pixelSize: tscale(12)
        horizontalAlignment: Text.AlignHCenter
    }
}
